### ISSUE TITLE
Please rename this repository and organization

### ISSUE THREAD

**Issue by maximusk** [AngularID-CN/AngularID-CN#108]
Hey, I'm the founder of [Angular In Depth](https://angularindepth.com). Please rename this repository and organization as you're not part of AngularInDepth organization. Thanks!

**Comment by lx1036** [comment]
> Hey, I'm the founder of [Angular In Depth](https://angularindepth.com). Please rename this repository and organization as you're not part of AngularInDepth organization. Thanks!

Hi Max,
**We have rename the repo and org name.**

Sorry for the trouble.

**Comment by maximusk** [comment]
Great, thanks a lot! Appreciate your quick reaction.
